[package]
name = "lh_persistence"
version.workspace = true
edition.workspace = true

[dependencies]
lh_core = { path = "../core" }
rusqlite = { version = "0.37.0", features = ["bundled"] }
chrono = "0.4"

[dev-dependencies]
tempfile = "3.8"
