[package]
name = "gui"
version.workspace = true
edition.workspace = true

[dependencies]
lh_api = { path = "../api" }
lh_core = { path = "../core" }

iced = { version = "0.13", features = ["tokio", "lazy"] }
thiserror = { workspace = true }
