[package]
name = "gui"
version.workspace = true
edition.workspace = true

[dependencies]
api = { path = "../api" }

iced = { version = "0.13", features = ["tokio", "lazy"] }
thiserror = { workspace = true }
